---
- name: RackHD Demonstration Server
  hosts: local
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - rackhd-packages
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - images
    - integrationtest
    - postgresql
