---
# vagrant ansible uses 1.5, which doesn't have the keyserver option enabled
- shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61"
  sudo: yes

# apt_repository apparently requires this to run in Ansible 1.5
- apt: pkg=python-pycurl state=present
  sudo: yes

- apt_repository: repo="deb https://dl.bintray.com/rackhd-mirror/debian trusty release"
                  state=present
  sudo: yes

- name: Install RackHD Packages latest
  shell: |
    set timeout -1
    spawn sudo aptitude install {{ item }}
    expect {
        "*Do you want to continue*" {send "y\r";set latest 1}
        "*Accept this solution*" {send "n\r"; set latest 0}
    }
    if { $latest == 0 } {
        expect "*Accept this solution*" {send "Y\r"}
        expect "*Do you want to continue*" {send "Y\r"}
    }
    expect {
        "*To continue*" {send "Yes\r"}
    }
    expect eof
    catch wait result
    exit [lindex $result 3]
  args:
    executable: /usr/bin/expect
  with_items:
    - rackhd
  sudo: yes
  when: (rackhd_version is undefined) or (not rackhd_version)

- name: Install RackHD Packages specific version
  shell: |
    set timeout -1
    spawn sudo aptitude install {{ item }}
    expect {
        "*Do you want to continue*" {send "y\r";set latest 1}
        "*Accept this solution*" {send "n\r"; set latest 0}
    }
    if { $latest == 0 } {
        expect "*Accept this solution*" {send "Y\r"}
        expect "*Do you want to continue*" {send "Y\r"}
    }
    expect {
        "*To continue*" {send "Yes\r"}
    }
    expect eof
    catch wait result
    exit [lindex $result 3]
  args:
    executable: /usr/bin/expect
  with_items:
    - rackhd={{ rackhd_version }}
  sudo: yes
  when: (rackhd_version is not undefined) and rackhd_version